### ISSUE TITLE
Error when use with Megui autoload

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/MPEG2DecPlus#3]
When i add this plugin and renamed to DGDecode.dll in Megui/tools/dgindex, i meet error when use megui autoload video cause you change plugin name to D2VSource. Can you add more one name plugin to MPEG2Source??

**Comment by Asd-g** [comment]
You can use https://github.com/Asd-g/MPEG2DecPlus/releases/tag/0.1.2 It has the same functionality as the renamed version.

**Comment by kedaitinh12** [comment]
But i can't update new function in the future

**Comment by Asd-g** [comment]
The reason for the renaming is to distinguish this version from the original plugin because there are differences breaking the backward compatibility.

If you want to use D2VSource with MeGUI you can do:
1. Don't remove the original DGDecode.dll.
2. Copy D2VSource.dll in the same folder where DGDecode.dll is placed.
3. Index the file as usual.
4. Go to "Script" on "AviSynth script creator" window.
5. Change DGDecode.dll to D2VSource.dll.
6. Change DGDecode_mpeg2source to D2VSource.

**Comment by realfinder** [comment]
> 
> 
> But i can't update new function in the future

when Megui will be updated it should use the new name, the old name don't even make sense since it not work with mpeg2 directly (it need index file in d2v), and it also not only support mpeg2 but also mpeg1

**Comment by kedaitinh12** [comment]
I'm waiting for new update megui
